

function renderFeuerwehr(){
  const e=canWrite("Feuerwehr"),t=canDelete("Feuerwehr"),n=DB.feuerwehr_reports;
  return`\n    <div class="section-header"><div><h2>Fire Department</h2><div class="sub">Einsatzberichte &amp; Lagemeldungen – nur Feuerwehr kann Berichte erstellen</div></div>\n      <button class="btn btn-primary" onclick="openFeuerwehrForm()" ${e?"":"disabled"}>\n        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>\n        Neuer Einsatzbericht\n      </button>\n    </div>\n    ${n.length?n.map(e=>`\n      <div class="card einsatz-card">\n        <div class="einsatz-top">\n          <div class="einsatz-title">\n            <span class="badge orange">${esc(e.art)}</span>\n            <span class="badge ${alarmstufeBadge(e.alarmstufe)}">${esc(e.alarmstufe||"Stufe 1")}</span>\n            <span class="status-pill ${"Abgeschlossen"===e.status?"off":"on"}">${esc(e.status||"Laufend")}</span>\n          </div>\n          ${t?`<button class="btn btn-ghost btn-sm" onclick="deleteFeuerwehr('${e.id}')">Löschen</button>`:""}\n        </div>\n        <h3 class="einsatz-ort">${esc(e.ort)}</h3>\n        <div class="einsatz-meta-grid">\n          <div><label>Einsatzleiter</label><span>${e.einsatzleiter?esc(e.einsatzleiter):"–"}</span></div>\n          <div><label>Kräfte / Fahrzeuge</label><span>${e.kraefte?esc(e.kraefte):"–"}</span></div>\n          <div><label>Verletzte / Betroffene</label><span>${e.verletzte?esc(e.verletzte):"0"}</span></div>\n        </div>\n        ${e.verlauf?`<p class="einsatz-verlauf">${esc(e.verlauf)}</p>`:""}\n        <div class="einsatz-footer">${esc(e.author)} · ${fmtDate(e.datum)}</div>\n      </div>`).join(""):'<div class="card"><div class="empty-state">Noch keine Einsatzberichte vorhanden.</div></div>'}`
}

function alarmstufeBadge(e){
  return"Stufe 3"===e||"Stufe 4"===e||"Großschadensereignis"===e?"red":"Stufe 2"===e?"orange":"gray"
}

function openFeuerwehrForm(){
  canWrite("Feuerwehr")?openFormModal("Neuer Einsatzbericht",[{key:"ort",label:"Ort",required:!0,placeholder:"Straße, Gebäude, Kreuzung …"},{key:"art",label:"Art des Einsatzes",type:"select",options:["Brand","Verkehrsunfall","Rettungseinsatz","Lagemeldung","Fehlalarm","Sonstiges"]},{key:"alarmstufe",label:"Alarmstufe",type:"select",value:"Stufe 1",options:["Stufe 1","Stufe 2","Stufe 3","Stufe 4","Großschadensereignis"]},{key:"einsatzleiter",label:"Einsatzleiter",placeholder:"Name des Einsatzleiters"},{key:"kraefte",label:"Eingesetzte Kräfte / Fahrzeuge",placeholder:"z. B. LF20, DLK, RTW"},{key:"verletzte",label:"Verletzte / Betroffene",type:"number",value:"0"},{key:"status",label:"Status",type:"select",value:"Laufend",options:["Laufend","Abgeschlossen"]},{key:"verlauf",label:"Verlauf / Lagemeldung",type:"textarea",placeholder:"Was ist passiert, welche Maßnahmen wurden getroffen …"}],async e=>{DB.feuerwehr_reports.unshift({id:genId(),ort:e.ort,art:e.art,alarmstufe:e.alarmstufe,einsatzleiter:e.einsatzleiter,kraefte:e.kraefte,verletzte:Number(e.verletzte)||0,status:e.status,verlauf:e.verlauf,author:currentAccount().displayName,datum:(new Date).toISOString()}),await persist("feuerwehr_reports"),logActivity(`Einsatzbericht (${e.art}) in ${e.ort} erstellt.`),renderPage()},"Speichern"):alert("Nur Feuerwehr-Charaktere können Einsatzberichte erstellen.")
}

async function deleteFeuerwehr(e){
  canDelete("Feuerwehr")&&confirm("Bericht wirklich löschen?")&&(DB.feuerwehr_reports=DB.feuerwehr_reports.filter(t=>t.id!==e),await persist("feuerwehr_reports"),renderPage())
}
